### ISSUE TITLE
VLCS Dataset

### ISSUE THREAD

**Issue by nathansomavarapu** [mil-tokyo/dg_mmld#3]
Hi,

I wanted to try your method on the VLCS dataset, as described in your paper, but I am having a hard time finding the dataset. Can you point me to where you get the dataset?

Thanks!

**Comment by Toshihiko-Matsuura** [comment]
Hi,

I could not find the VLCS dataset, so I got it from another domain generalization researcher.
If you send me an e-mail, I will tell you the URL, where I uploaded the dataset.

Thank you.

**Comment by Arfeen93** [comment]
> Hi,
> 
> I could not find the VLCS dataset, so I got it from another domain generalization researcher.
> If you send me an e-mail, I will tell you a URL where I uploaded the dataset.
> 
> Thank you.

Hi,

Can you send me the link where VLCS dataset is uploaded. Email id is faizularefeen@gmail.com.

Thanks!

**Comment by mingsgen** [comment]
> Hi,
> 
> I could not find the VLCS dataset, so I got it from another domain generalization researcher.
> If you send me an e-mail, I will tell you a URL where I uploaded the dataset.
> 
> Thank you.

Hi,

Can you send me where VLCS dataset is uploaded. Email id is msg0@mail.ustc.edu.cn
By the way, I can't find the PACS dataset anywhere. it will be very appreciate if you send me the PACS dataset, too.
